sonar.projectKey=Chaos-Pizza-API-ETM
sonar.projectName=Chaos Pizza API ETM
sonar.sources=.
sonar.tests=test
sonar.exclusions=test/**
# LCOV report produced by Jest (coverage/lcov.info by default)
sonar.javascript.lcov.reportPaths=coverage/lcov.info